# 应用访问端口号
server:
  port: 8080
# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.1.115:3306/dubhe
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
